/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.ucsb.cs.rpc.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DataObject implements org.apache.thrift.TBase<DataObject, DataObject._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataObject");

  private static final org.apache.thrift.protocol.TField STR_FIELD_DESC = new org.apache.thrift.protocol.TField("str", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("number", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField DECIMAL_FIELD_DESC = new org.apache.thrift.protocol.TField("decimal", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField CHARACTER_FIELD_DESC = new org.apache.thrift.protocol.TField("character", org.apache.thrift.protocol.TType.BYTE, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DataObjectStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DataObjectTupleSchemeFactory());
  }

  public String str; // required
  public int number; // required
  public double decimal; // required
  public byte character; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STR((short)1, "str"),
    NUMBER((short)2, "number"),
    DECIMAL((short)3, "decimal"),
    CHARACTER((short)4, "character");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STR
          return STR;
        case 2: // NUMBER
          return NUMBER;
        case 3: // DECIMAL
          return DECIMAL;
        case 4: // CHARACTER
          return CHARACTER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMBER_ISSET_ID = 0;
  private static final int __DECIMAL_ISSET_ID = 1;
  private static final int __CHARACTER_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STR, new org.apache.thrift.meta_data.FieldMetaData("str", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NUMBER, new org.apache.thrift.meta_data.FieldMetaData("number", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DECIMAL, new org.apache.thrift.meta_data.FieldMetaData("decimal", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CHARACTER, new org.apache.thrift.meta_data.FieldMetaData("character", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataObject.class, metaDataMap);
  }

  public DataObject() {
  }

  public DataObject(
    String str,
    int number,
    double decimal,
    byte character)
  {
    this();
    this.str = str;
    this.number = number;
    setNumberIsSet(true);
    this.decimal = decimal;
    setDecimalIsSet(true);
    this.character = character;
    setCharacterIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DataObject(DataObject other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetStr()) {
      this.str = other.str;
    }
    this.number = other.number;
    this.decimal = other.decimal;
    this.character = other.character;
  }

  public DataObject deepCopy() {
    return new DataObject(this);
  }

  @Override
  public void clear() {
    this.str = null;
    setNumberIsSet(false);
    this.number = 0;
    setDecimalIsSet(false);
    this.decimal = 0.0;
    setCharacterIsSet(false);
    this.character = 0;
  }

  public String getStr() {
    return this.str;
  }

  public DataObject setStr(String str) {
    this.str = str;
    return this;
  }

  public void unsetStr() {
    this.str = null;
  }

  /** Returns true if field str is set (has been assigned a value) and false otherwise */
  public boolean isSetStr() {
    return this.str != null;
  }

  public void setStrIsSet(boolean value) {
    if (!value) {
      this.str = null;
    }
  }

  public int getNumber() {
    return this.number;
  }

  public DataObject setNumber(int number) {
    this.number = number;
    setNumberIsSet(true);
    return this;
  }

  public void unsetNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUMBER_ISSET_ID);
  }

  /** Returns true if field number is set (has been assigned a value) and false otherwise */
  public boolean isSetNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __NUMBER_ISSET_ID);
  }

  public void setNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUMBER_ISSET_ID, value);
  }

  public double getDecimal() {
    return this.decimal;
  }

  public DataObject setDecimal(double decimal) {
    this.decimal = decimal;
    setDecimalIsSet(true);
    return this;
  }

  public void unsetDecimal() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DECIMAL_ISSET_ID);
  }

  /** Returns true if field decimal is set (has been assigned a value) and false otherwise */
  public boolean isSetDecimal() {
    return EncodingUtils.testBit(__isset_bitfield, __DECIMAL_ISSET_ID);
  }

  public void setDecimalIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DECIMAL_ISSET_ID, value);
  }

  public byte getCharacter() {
    return this.character;
  }

  public DataObject setCharacter(byte character) {
    this.character = character;
    setCharacterIsSet(true);
    return this;
  }

  public void unsetCharacter() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CHARACTER_ISSET_ID);
  }

  /** Returns true if field character is set (has been assigned a value) and false otherwise */
  public boolean isSetCharacter() {
    return EncodingUtils.testBit(__isset_bitfield, __CHARACTER_ISSET_ID);
  }

  public void setCharacterIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CHARACTER_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STR:
      if (value == null) {
        unsetStr();
      } else {
        setStr((String)value);
      }
      break;

    case NUMBER:
      if (value == null) {
        unsetNumber();
      } else {
        setNumber((Integer)value);
      }
      break;

    case DECIMAL:
      if (value == null) {
        unsetDecimal();
      } else {
        setDecimal((Double)value);
      }
      break;

    case CHARACTER:
      if (value == null) {
        unsetCharacter();
      } else {
        setCharacter((Byte)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STR:
      return getStr();

    case NUMBER:
      return Integer.valueOf(getNumber());

    case DECIMAL:
      return Double.valueOf(getDecimal());

    case CHARACTER:
      return Byte.valueOf(getCharacter());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STR:
      return isSetStr();
    case NUMBER:
      return isSetNumber();
    case DECIMAL:
      return isSetDecimal();
    case CHARACTER:
      return isSetCharacter();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DataObject)
      return this.equals((DataObject)that);
    return false;
  }

  public boolean equals(DataObject that) {
    if (that == null)
      return false;

    boolean this_present_str = true && this.isSetStr();
    boolean that_present_str = true && that.isSetStr();
    if (this_present_str || that_present_str) {
      if (!(this_present_str && that_present_str))
        return false;
      if (!this.str.equals(that.str))
        return false;
    }

    boolean this_present_number = true;
    boolean that_present_number = true;
    if (this_present_number || that_present_number) {
      if (!(this_present_number && that_present_number))
        return false;
      if (this.number != that.number)
        return false;
    }

    boolean this_present_decimal = true;
    boolean that_present_decimal = true;
    if (this_present_decimal || that_present_decimal) {
      if (!(this_present_decimal && that_present_decimal))
        return false;
      if (this.decimal != that.decimal)
        return false;
    }

    boolean this_present_character = true;
    boolean that_present_character = true;
    if (this_present_character || that_present_character) {
      if (!(this_present_character && that_present_character))
        return false;
      if (this.character != that.character)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(DataObject other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    DataObject typedOther = (DataObject)other;

    lastComparison = Boolean.valueOf(isSetStr()).compareTo(typedOther.isSetStr());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStr()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.str, typedOther.str);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNumber()).compareTo(typedOther.isSetNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.number, typedOther.number);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDecimal()).compareTo(typedOther.isSetDecimal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDecimal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.decimal, typedOther.decimal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCharacter()).compareTo(typedOther.isSetCharacter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCharacter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.character, typedOther.character);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DataObject(");
    boolean first = true;

    sb.append("str:");
    if (this.str == null) {
      sb.append("null");
    } else {
      sb.append(this.str);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("number:");
    sb.append(this.number);
    first = false;
    if (!first) sb.append(", ");
    sb.append("decimal:");
    sb.append(this.decimal);
    first = false;
    if (!first) sb.append(", ");
    sb.append("character:");
    sb.append(this.character);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DataObjectStandardSchemeFactory implements SchemeFactory {
    public DataObjectStandardScheme getScheme() {
      return new DataObjectStandardScheme();
    }
  }

  private static class DataObjectStandardScheme extends StandardScheme<DataObject> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DataObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.str = iprot.readString();
              struct.setStrIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.number = iprot.readI32();
              struct.setNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DECIMAL
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.decimal = iprot.readDouble();
              struct.setDecimalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CHARACTER
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.character = iprot.readByte();
              struct.setCharacterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DataObject struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.str != null) {
        oprot.writeFieldBegin(STR_FIELD_DESC);
        oprot.writeString(struct.str);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NUMBER_FIELD_DESC);
      oprot.writeI32(struct.number);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DECIMAL_FIELD_DESC);
      oprot.writeDouble(struct.decimal);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CHARACTER_FIELD_DESC);
      oprot.writeByte(struct.character);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DataObjectTupleSchemeFactory implements SchemeFactory {
    public DataObjectTupleScheme getScheme() {
      return new DataObjectTupleScheme();
    }
  }

  private static class DataObjectTupleScheme extends TupleScheme<DataObject> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DataObject struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStr()) {
        optionals.set(0);
      }
      if (struct.isSetNumber()) {
        optionals.set(1);
      }
      if (struct.isSetDecimal()) {
        optionals.set(2);
      }
      if (struct.isSetCharacter()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetStr()) {
        oprot.writeString(struct.str);
      }
      if (struct.isSetNumber()) {
        oprot.writeI32(struct.number);
      }
      if (struct.isSetDecimal()) {
        oprot.writeDouble(struct.decimal);
      }
      if (struct.isSetCharacter()) {
        oprot.writeByte(struct.character);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DataObject struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.str = iprot.readString();
        struct.setStrIsSet(true);
      }
      if (incoming.get(1)) {
        struct.number = iprot.readI32();
        struct.setNumberIsSet(true);
      }
      if (incoming.get(2)) {
        struct.decimal = iprot.readDouble();
        struct.setDecimalIsSet(true);
      }
      if (incoming.get(3)) {
        struct.character = iprot.readByte();
        struct.setCharacterIsSet(true);
      }
    }
  }

}

