// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `EchoHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package edu.ucsb.cs.rpc.ice.service;

public final class EchoHolder extends Ice.ObjectHolderBase<Echo>
{
    public
    EchoHolder()
    {
    }

    public
    EchoHolder(Echo value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        try
        {
            value = (Echo)v;
        }
        catch(ClassCastException ex)
        {
            IceInternal.Ex.throwUOE(type(), v.ice_id());
        }
    }

    public String
    type()
    {
        return _EchoDisp.ice_staticId();
    }
}
