// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/Echo.proto

package edu.ucsb.cs.rpc.protobuf;

public final class Echo {
  private Echo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NothingMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class NothingMessage extends
      com.google.protobuf.GeneratedMessage
      implements NothingMessageOrBuilder {
    // Use NothingMessage.newBuilder() to construct.
    private NothingMessage(Builder builder) {
      super(builder);
    }
    private NothingMessage(boolean noInit) {}
    
    private static final NothingMessage defaultInstance;
    public static NothingMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public NothingMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_NothingMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_NothingMessage_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucsb.cs.rpc.protobuf.Echo.NothingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_NothingMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_NothingMessage_fieldAccessorTable;
      }
      
      // Construct using edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDescriptor();
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage getDefaultInstanceForType() {
        return edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance();
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage build() {
        edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage buildPartial() {
        edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage result = new edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage) {
          return mergeFrom((edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage other) {
        if (other == edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:NothingMessage)
    }
    
    static {
      defaultInstance = new NothingMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NothingMessage)
  }
  
  public interface EchoStringOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string data = 1;
    boolean hasData();
    String getData();
  }
  public static final class EchoString extends
      com.google.protobuf.GeneratedMessage
      implements EchoStringOrBuilder {
    // Use EchoString.newBuilder() to construct.
    private EchoString(Builder builder) {
      super(builder);
    }
    private EchoString(boolean noInit) {}
    
    private static final EchoString defaultInstance;
    public static EchoString getDefaultInstance() {
      return defaultInstance;
    }
    
    public EchoString getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoString_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoString_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucsb.cs.rpc.protobuf.Echo.EchoString prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucsb.cs.rpc.protobuf.Echo.EchoStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoString_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoString_fieldAccessorTable;
      }
      
      // Construct using edu.ucsb.cs.rpc.protobuf.Echo.EchoString.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDescriptor();
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoString getDefaultInstanceForType() {
        return edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance();
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoString build() {
        edu.ucsb.cs.rpc.protobuf.Echo.EchoString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucsb.cs.rpc.protobuf.Echo.EchoString buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucsb.cs.rpc.protobuf.Echo.EchoString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoString buildPartial() {
        edu.ucsb.cs.rpc.protobuf.Echo.EchoString result = new edu.ucsb.cs.rpc.protobuf.Echo.EchoString(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucsb.cs.rpc.protobuf.Echo.EchoString) {
          return mergeFrom((edu.ucsb.cs.rpc.protobuf.Echo.EchoString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucsb.cs.rpc.protobuf.Echo.EchoString other) {
        if (other == edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string data = 1;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:EchoString)
    }
    
    static {
      defaultInstance = new EchoString(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EchoString)
  }
  
  public interface EchoIntOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 data = 1;
    boolean hasData();
    int getData();
  }
  public static final class EchoInt extends
      com.google.protobuf.GeneratedMessage
      implements EchoIntOrBuilder {
    // Use EchoInt.newBuilder() to construct.
    private EchoInt(Builder builder) {
      super(builder);
    }
    private EchoInt(boolean noInit) {}
    
    private static final EchoInt defaultInstance;
    public static EchoInt getDefaultInstance() {
      return defaultInstance;
    }
    
    public EchoInt getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoInt_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoInt_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private int data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getData() {
      return data_;
    }
    
    private void initFields() {
      data_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucsb.cs.rpc.protobuf.Echo.EchoInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucsb.cs.rpc.protobuf.Echo.EchoInt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucsb.cs.rpc.protobuf.Echo.EchoIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoInt_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucsb.cs.rpc.protobuf.Echo.internal_static_EchoInt_fieldAccessorTable;
      }
      
      // Construct using edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDescriptor();
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoInt getDefaultInstanceForType() {
        return edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance();
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoInt build() {
        edu.ucsb.cs.rpc.protobuf.Echo.EchoInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.ucsb.cs.rpc.protobuf.Echo.EchoInt buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.ucsb.cs.rpc.protobuf.Echo.EchoInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoInt buildPartial() {
        edu.ucsb.cs.rpc.protobuf.Echo.EchoInt result = new edu.ucsb.cs.rpc.protobuf.Echo.EchoInt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucsb.cs.rpc.protobuf.Echo.EchoInt) {
          return mergeFrom((edu.ucsb.cs.rpc.protobuf.Echo.EchoInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.ucsb.cs.rpc.protobuf.Echo.EchoInt other) {
        if (other == edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              data_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 data = 1;
      private int data_ ;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getData() {
        return data_;
      }
      public Builder setData(int value) {
        bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EchoInt)
    }
    
    static {
      defaultInstance = new EchoInt(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EchoInt)
  }
  
  public static abstract class EchoService
      implements com.google.protobuf.Service {
    protected EchoService() {}
    
    public interface Interface {
      public abstract void doNothing(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage request,
          com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage> done);
      
      public abstract void echoString(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoString request,
          com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoString> done);
      
      public abstract void echoInt(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoInt request,
          com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoInt> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new EchoService() {
        @java.lang.Override
        public  void doNothing(
            com.google.protobuf.RpcController controller,
            edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage request,
            com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage> done) {
          impl.doNothing(controller, request, done);
        }
        
        @java.lang.Override
        public  void echoString(
            com.google.protobuf.RpcController controller,
            edu.ucsb.cs.rpc.protobuf.Echo.EchoString request,
            com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoString> done) {
          impl.echoString(controller, request, done);
        }
        
        @java.lang.Override
        public  void echoInt(
            com.google.protobuf.RpcController controller,
            edu.ucsb.cs.rpc.protobuf.Echo.EchoInt request,
            com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoInt> done) {
          impl.echoInt(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.doNothing(controller, (edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage)request);
            case 1:
              return impl.echoString(controller, (edu.ucsb.cs.rpc.protobuf.Echo.EchoString)request);
            case 2:
              return impl.echoInt(controller, (edu.ucsb.cs.rpc.protobuf.Echo.EchoInt)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance();
            case 1:
              return edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance();
            case 2:
              return edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance();
            case 1:
              return edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance();
            case 2:
              return edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void doNothing(
        com.google.protobuf.RpcController controller,
        edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage request,
        com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage> done);
    
    public abstract void echoString(
        com.google.protobuf.RpcController controller,
        edu.ucsb.cs.rpc.protobuf.Echo.EchoString request,
        com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoString> done);
    
    public abstract void echoInt(
        com.google.protobuf.RpcController controller,
        edu.ucsb.cs.rpc.protobuf.Echo.EchoInt request,
        com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoInt> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return edu.ucsb.cs.rpc.protobuf.Echo.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.doNothing(controller, (edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage)request,
            com.google.protobuf.RpcUtil.<edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage>specializeCallback(
              done));
          return;
        case 1:
          this.echoString(controller, (edu.ucsb.cs.rpc.protobuf.Echo.EchoString)request,
            com.google.protobuf.RpcUtil.<edu.ucsb.cs.rpc.protobuf.Echo.EchoString>specializeCallback(
              done));
          return;
        case 2:
          this.echoInt(controller, (edu.ucsb.cs.rpc.protobuf.Echo.EchoInt)request,
            com.google.protobuf.RpcUtil.<edu.ucsb.cs.rpc.protobuf.Echo.EchoInt>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance();
        case 1:
          return edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance();
        case 2:
          return edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance();
        case 1:
          return edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance();
        case 2:
          return edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends edu.ucsb.cs.rpc.protobuf.Echo.EchoService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void doNothing(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage request,
          com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.class,
            edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance()));
      }
      
      public  void echoString(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoString request,
          com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoString> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.ucsb.cs.rpc.protobuf.Echo.EchoString.class,
            edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance()));
      }
      
      public  void echoInt(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoInt request,
          com.google.protobuf.RpcCallback<edu.ucsb.cs.rpc.protobuf.Echo.EchoInt> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.class,
            edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage doNothing(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage request)
          throws com.google.protobuf.ServiceException;
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoString echoString(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoString request)
          throws com.google.protobuf.ServiceException;
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoInt echoInt(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoInt request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage doNothing(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage request)
          throws com.google.protobuf.ServiceException {
        return (edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.getDefaultInstance());
      }
      
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoString echoString(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoString request)
          throws com.google.protobuf.ServiceException {
        return (edu.ucsb.cs.rpc.protobuf.Echo.EchoString) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoString.getDefaultInstance());
      }
      
      
      public edu.ucsb.cs.rpc.protobuf.Echo.EchoInt echoInt(
          com.google.protobuf.RpcController controller,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoInt request)
          throws com.google.protobuf.ServiceException {
        return (edu.ucsb.cs.rpc.protobuf.Echo.EchoInt) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NothingMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NothingMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoString_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EchoString_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoInt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EchoInt_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025main/proto/Echo.proto\"\020\n\016NothingMessag" +
      "e\"\032\n\nEchoString\022\014\n\004data\030\001 \002(\t\"\027\n\007EchoInt" +
      "\022\014\n\004data\030\001 \002(\0052\203\001\n\013EchoService\022-\n\tdoNoth" +
      "ing\022\017.NothingMessage\032\017.NothingMessage\022&\n" +
      "\nechoString\022\013.EchoString\032\013.EchoString\022\035\n" +
      "\007echoInt\022\010.EchoInt\032\010.EchoIntB#\n\030edu.ucsb" +
      ".cs.rpc.protobufB\004Echo\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NothingMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NothingMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NothingMessage_descriptor,
              new java.lang.String[] { },
              edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.class,
              edu.ucsb.cs.rpc.protobuf.Echo.NothingMessage.Builder.class);
          internal_static_EchoString_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_EchoString_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EchoString_descriptor,
              new java.lang.String[] { "Data", },
              edu.ucsb.cs.rpc.protobuf.Echo.EchoString.class,
              edu.ucsb.cs.rpc.protobuf.Echo.EchoString.Builder.class);
          internal_static_EchoInt_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_EchoInt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EchoInt_descriptor,
              new java.lang.String[] { "Data", },
              edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.class,
              edu.ucsb.cs.rpc.protobuf.Echo.EchoInt.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
